var selectedTexts = [];
const chapterTexts = {
    '1.1': 'By this art you may contemplate the variations of the 23 letters...',
    '1.2': 'The Anatomy of Melancholy, part 2, sect. II, mem. IV',
    '2.1': 'The universe (which others call the Library) is composed of an indefinite and perhaps infinite number of hexagonal galleries, with vast air shafts between, surrounded by very low railings.',
    '2.2': 'From any of the hexagons one can see, interminably, the upper and lower floors.',
    '2.3': 'The distribution of the galleries is invariable. Twenty shelves, five long shelves per side, cover all the sides except two; their height, which is the distance from floor to ceiling, scarcely exceeds that of a normal bookcase.',
    '2.4': 'One of the free sides leads to a narrow hallway which opens onto another gallery, identical to the first and to all the rest.',
    '2.5': 'To the left and right of the hallway there are two very small closets.',
    '2.6': 'In the first, one may sleep standing up; in the other, satisfy ones fecal necessities.',
    '2.7': 'Also through here passes a spiral stairway, which sinks abysmally and soars upwards to remote distances.',
    '2.8': 'In the hallway there is a mirror which faithfully duplicates all appearances.',
    '2.9': 'Men usually infer from this mirror that the Library is not infinite (if it were, why this illusory duplication?); I prefer to dream that its polished surfaces represent and promise the infinite... Light is provided by some spherical fruit which bear the name of lamps. There are two, transversally placed, in each hexagon.',
    '2.10':' The light they emit is insufficient, incessant.',
    '3.1': 'Like all men of the Library, I have traveled in my youth; I have wandered in search of a book, perhaps the catalogue of catalogues; now that my eyes can hardly decipher what I write, I am preparing to die just a few leagues from the hexagon in which I was born.',
    '3.2': 'Once I am dead, there will be no lack of pious hands to throw me over the railing; my grave will be the fathomless air; my body will sink endlessly and decay and dissolve in the wind generated by the fall, which is infinite.',
  
  };
  
  function displayText(chapter) {
    const textDisplay = document.getElementById('text-display');
    const newText = document.createElement('p');
    newText.textContent = chapterTexts[chapter];
    textDisplay.appendChild(newText);
    selectedTexts.push(newText);
  }
  
function clearText() {
  const textDisplay = document.getElementById('text-display');
  textDisplay.innerHTML = '';
  selectedTexts = [];
}
function reverseSelection() {
    const lastSelected = selectedTexts.pop();
    if (lastSelected) {
      lastSelected.remove();
    }
}

document.getElementById('clear-button').addEventListener('click', clearText);
document.getElementById('reverse-button').addEventListener('click', reverseSelection);
